app:
  lucene:
    refreshIndexMin: 10
    indexFilePath: "/dev/shm/lucene"
    hitsToReturn: 100

  thisAppNumber: ${thisAppNumber}

management:
 context-path: /manage
 security:
    enabled: false

security:
  basic:
    enabled: false